### ISSUE TITLE
"Sorry, the meetup list isn't available right now"

### ISSUE THREAD

**Issue by erose** [ssc-meetups-community/ssc-meetups-widget#1]
As of the time of writing, I'm seeing this on slatestarcodex.com

![image](https://user-images.githubusercontent.com/1514487/62742285-ffc4b980-ba0b-11e9-95cc-29d24723ec61.png)

Console doesn't display any errors.

**Comment by taymonbeal** [comment]
This is a known issue and was fixed in d5d2266844ecb358e9d1d17ca26159089ffd1ee0. Unfortunately, the continuous deployment system isn't working properly, so the live SSC site doesn't have the fix yet. I'm working on getting it deployed.

**Comment by erose** [comment]
Gotcha -- thanks!

**Comment by taymonbeal** [comment]
Okay, fix is live.
